In [ ]:
## import numpy

In [2]:
import numpy as np

In [3]:
## Create an array of 10 zeros

In [6]:
array_of_10_zeros = np.zeros(10)
print(array_of_10_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
## Create an array of 10 ones

In [8]:
array_of_10_ones = np.ones(10)
print(array_of_10_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
## Create an array of 10 fives

In [9]:
array_of_10_fives = np.ones(10)*5
print(array_of_10_fives)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
## Create an array of the integers from 10 to 50

In [17]:
array_of_int_10_to_50 = np.arange(10,51,1)
print(array_of_int_10_to_50)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [18]:
## Create an array of all even integers from 10 to 50

In [19]:
array_of_even_int_10_to_50 = np.arange(10,51,2)
print(array_of_even_int_10_to_50)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [20]:
## Create a 3x3 matrix with values ranging from 0 to 8

In [25]:
matrix_range_from_0_to_8 =  np.arange(0, 9).reshape(3,3)
#an array of the size 8 can not be reshaped to 3x3. So the length will be 9
print(matrix_range_from_0_to_8)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
## Create a 3x3 identity matrix

In [28]:
identity_matrix =  np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
## Use NumPy to generate a random number between 0 and 1

In [29]:
rand_num = np.random.normal(0,1,1)
print(rand_num)

[-0.4639445]


In [ ]:
## Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [32]:
array_of_25_random_nums = np.random.normal(0,1,25)
print(array_of_25_random_nums)

[ 0.75828001 -0.08343846 -0.55730909 -0.65361055  0.52406978 -0.97616907
 -0.04188368  1.74558972 -0.78961732  0.77111812 -1.38557049  0.88436318
 -0.64305923  0.53060823 -0.09234877  0.10386608  0.75989896 -1.25172429
 -1.04549244  0.83721356  1.55002993  0.45292506 -0.03325966 -0.67590464
 -0.06397587]


In [ ]:
## Create an array of 20 linearly spaced points between 0 and 1:

In [33]:
linearly_spaced_points = np.linspace(0, 1, 20)
print(linearly_spaced_points)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]
